limits:
  minimum: 1
  maximum: 1000
spring:
  application:
    name: limits-service
  config:
    #import: configserver:http://localhost:8888
    import: optional:configserver:http://localhost:8888
  profiles:
    active: qa
#  cloud:
#    config:
#      profile: qa