server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///Users/srm/Documents/Estudios/Cursos/Spring Cloud/config-server-git